In [36]:
import pandas as pd

df = pd.read_csv("matches-2003-2025.csv", sep = ";", encoding = "latin1")

df.shape

(9166, 5)

In [40]:

df.head()

        #DATE   HOUR       HOME-TEAM SCORE    AWAY-TEAM
0  29/03/2003  18:00      Guarani/SP   4x2     Vasco/RJ
1  29/03/2003  18:00     Atlético/PR   2x0    Grêmio/RS
2  30/03/2003  18:00        Goiás/GO   2x2  Paysandu/PA
3  30/03/2003  18:00  Corinthians/SP   0x3  Atlético/MG
4  30/03/2003  16:00     Flamengo/RJ   1x1  Coritiba/PR

In [48]:
df.dtypes

#DATE        datetime64[ns]
HOUR                 object
HOME-TEAM            object
SCORE                object
AWAY-TEAM            object
dtype: object

In [43]:
df["#DATE"].head()

0    29/03/2003
1    29/03/2003
2    30/03/2003
3    30/03/2003
4    30/03/2003
Name: #DATE, dtype: object

In [47]:
df["#DATE"] = pd.to_datetime(df["#DATE"])
df["#DATE"]

0      2003-03-29
1      2003-03-29
2      2003-03-30
3      2003-03-30
4      2003-03-30
          ...
9161   2025-12-07
9162   2025-12-07
9163   2025-12-07
9164   2025-12-07
9165   2025-12-07
Name: #DATE, Length: 9166, dtype: datetime64[ns]

In [50]:

def verifica_resultado(resultado):
  placar = resultado.split("x")

  casa = int(placar[0])
  visitante = int(placar[1])

  if casa > visitante:
    resultado_visitante = "derrota"
  elif casa == visitante:
    resultado_visitante = "empate"
  else:
    resultado_visitante = "vitoria"

  return resultado_visitante

In [52]:
df["RESULTADO_VISITANTE"] = df["SCORE"].apply(verifica_resultado)
df["RESULTADO_VISITANTE"]

0       derrota
1       derrota
2        empate
3       vitoria
4        empate
         ...
9161    derrota
9162    derrota
9163    derrota
9164    vitoria
9165    derrota
Name: RESULTADO_VISITANTE, Length: 9166, dtype: object